api-platform/api-platform

- composer.json
- composer.lock
A bug make the behat scenarios throw an error in the version 2.1.*
of behatch/contexts. Due to the removing of the later tags 2.2 and
2.3 as referenced in the issue behatch/contexts#126, the dependency
is set to dev-master for the moment.
Closes #13
> Fix behatch version

- app/config/config.yml
| Fixed tickets | n/a
Set CORS headers to allow exposing the `Link` header and enable JavaScript clients to retrieve the Hydra API doc.
> Expose the Link header (Hydra doc)

- docker/php/php.ini
This option has been removed since PHP 5.4
(Follow-up to #59)
> Remove register_globals option in php.ini

- app/config/routing.yml
If you add a custom itemOperation, the route will be before in the RouteCollection, and will be used for generating the @id attribute.
This patch move the custom routes after the api generated.
> Move Action loading after api

- app/config/routing.yml
> typo routing.yml

- app/config/config_test.yml
It was forgotten when moving to the structure of Symfony 3+.
> Configure the SQLite database for tests

- composer.json
- composer.lock
Finally, it's more user friendly to have the schema generator preinstalled than having to download an external phar.
> Install the Schema Generator by default and update dependencies

- docker/start.sh
In some cases when stopped, container running apache leaves a PID file behind. As a result, the next time the container starts, apache will stop because of the PID file left in place :
```
httpd (pid 48) already running
```
> Remove pre-existing PID file before starting apache

- docker/start.sh
Otherwise the `composer install` fail because `dev` is the env by default of Symfony but dev dependencies aren't installed.
> Always use the dev env if the SYMFONY_ENV var isn't set

- app/config/config_prod.yml
* Remove the comment regarding the framework section (not necessary anymore since 3.2)
* Switch to the apcu driver of Doctrine Cache (best default for PHP 7+ because it doesn't need the compatibility layer of APCu).
> Update config_prod.yml settings

- composer.json
- web/app.php
- web/app_dev.php
No need for conditionals because we require PHP >= 7.0
> Don't use ClassLoader component deprecated in Symfony 3.3

- app/config/api_filters.yml
- app/config/config.yml
- composer.json
- composer.lock
It prevents to have to define manually `autoconfigure`, `autowire` and other keys because of the new `_defaults` key introduced in the standard edition of Symfony 3.3.
> Introduce a new file to register filters

- .gitattributes
> Ensure git always uses LF for EOL in shell scripts

- api/composer.json
Symlinks don't play well with the Nginx container.
> Fix assets:install command for Docker in composer.json

- api/docker/php/docker-entrypoint.sh
This is necessary on Windows otherwise the following error occurs on docker-compose up
```
php_1          | Nothing to install or update
php_1          | Generating autoload files
php_1          | Executing script cache:clear [OK]
php_1          |
php_1          | Executing script assets:install [OK]
': No such file or directoryexecute 'php
> Fixed docker for Windows

- docker-compose.yaml
| Fixed tickets | - 
| Doc PR        | Didn't find impacted documentation
Remove ./ relative alternate dockerfile path notation which doesn't work on latest version of Docker + Compose
See: https://docs.docker.com/compose/compose-file/#dockerfile
> Fix dockerfile alternate paths

- api/Dockerfile
- api/docker/php/docker-entrypoint.sh
| BC breaks?    | not sure
| Fixed tickets | #628
To be consistant with sf4, the "logs" folder has been renamed to "log"
> Changed var/logs to var/log

- api/docker/php/php.ini
| Fixed tickets | -
| Doc PR        | -
`opcache.memory_consumption` is present on the [Symfony documentation](http://symfony.com/doc/current/performance.html#configure-opcache-for-maximum-performance) while `opcache.interned_strings_buffer` should be upgraded also as the default value is quite low.
That's basically exactly the same PR I did [here](https://github.com/dunglas/symfony-docker/pull/24). 😉
> Improve OPcache settings

- api/.env
- api/.env.dist
The current regex allows domains like `http://localhost8000` (missing `:`). This PR allows only `localhost` followed by a port.
Reported by @Mathieudewet.
> Fix NelmioCors regex

- api/config/packages/doctrine.yaml
- api/helm/api/requirements.lock
- api/helm/api/requirements.yaml
- api/helm/api/values.yaml
- docker-compose.yml
Previously this was downgraded to 9.6 with PR https://github.com/api-platform/api-platform/pull/532.
Doctrine now supports postgresql v10. Currently Heroku defaults to giving people v10 databases so I think it's a good idea to upgrade at this point as people setting up using the Heroku tutorials will eventually experience problems when doing things like updating their schemas.
> Upgrade to postgres 10

- api/docker/php/docker-entrypoint.sh
Follow up of #857 .
Will support things like `docker-compose run php php bin/console app:amazing-and-shiny-command`.
> Add support for php cli in docker-entrypoint

- api/Dockerfile
Install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching).
> Use Symfony Flex

- .travis.yml
- api/.env
Accidentally removed in #1023.
This also means we need a better smoke test, as the problem was not caught.
> Add back missing MERCURE_SUBSCRIBE_URL env var

- .editorconfig
- api/Dockerfile
- api/docker/varnish/conf/default.vcl
https://varnish-cache.org/docs/6.2/whats-new/upgrading-6.2.html
> `return(miss)` from `vcl_hit{}` is now removed. An option for implementing similar functionality is:
>
> * `return (restart)` from `vcl_hit{}`
> * in `vcl_recv{}` for the restart (when `req.restarts` has increased), `set req.hash_always_miss = true;`.
https://varnish-cache.org/docs/6.2/whats-new/changes-6.2.html#other-changes-to-vcl
> `return(miss)` from `vcl_hit{}` did never work as intended for the common case (it actually turned into a pass), so we now removed it and changed the `builtin.vcl`.
> Upgrade to Varnish 6.2

- docker-compose.yml
Fixes that error:
```
h2-proxy_1     | 2019/06/16 13:33:45 [emerg] 1#1: host not found in upstream "mercure" in /etc/nginx/conf.d/default.conf:76
h2-proxy_1     | nginx: [emerg] host not found in upstream "mercure" in /etc/nginx/conf.d/default.conf:76
sonda_h2-proxy_1 exited with code 1
```
> Fixes proxy error

- api/.env
Maybe I'm missing something, but this just ends up with single quotes in the regex, so it won't match any hostnames (on Windows at least).
See [CORS_ALLOW_ORIGIN](https://github.com/api-platform/api-platform/blob/767e635967019577952df7592725969c37b108f4/api/.env#L34) in the same file for an example of regex, and no other values in the `.env` are wrapped in single quotes.
> Remove quotes from TRUSTED_HOSTS

- api/Dockerfile
PHPUnit 8 is required for our new testing utilities.
> Use PHPUnit 8 by default

- api/helm/api/templates/configmap.yaml
Hey 👋 ,
i tried to install the helm charts without varnish --set varnish.enabled=false.
This caused into an error: 
```
Error: validation failed: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.varnish-url
```
It's more like a logical error.  If varnish is not enabled, it tries to use the varnish.url variable, which is not set, because i don't need it.
As a general question, is it better to use the if varnish.enabled block complete around the configmap key "varnish-url"?
Example:
```
{{ if .Values.varnish.enabled }}varnish-url: {{ if .Values.varnish.url }}{{ .Values.varnish.url | quote }}{{ else }}http://varnish{{ end }}{{ end }}
```
In this case, it  need some improvements in other files, because some parts depends that the config file varnish-url …
> Helm: Error if --set varnish.enabled=false - Logical error

- README.md
HAL stateless.co domain is suspended. Changed HAL url to their GitHub.
> Changed url to use secure links if supported

- .travis.yml
- api/Dockerfile
- api/docker/nginx/conf.d/default.conf
- api/helm/api/templates/varnish-deployment.yaml
Since there's an [official `varnish` Docker image](https://hub.docker.com/_/varnish) now, we should use it and abandon maintaining [our own image](https://hub.docker.com/r/cooptilleuls/varnish).
> Switch to the official varnish Docker image

- api/helm/api/values.yaml
I got an `Unauthorized error` and figured out I didn't set the Mercure JWT key. I propose to add the key to `values.yaml` so it will be less easy to miss.
> Add mercure.jwtKey

- .gitattributes
| Tickets       | fixes #1413 
| Doc PR        | na
I guess that this line skips the License in the archive.
> Keep LICENSE in archive

- .github/workflows/ci-cd.yml
Now the inline build cache works. Thanks @bendavies for your time.
Next step: Switch away from inline cache so that we can use `mode=max`?
> Switch to docker-container provider for buildx

- .github/workflows/ci-cd.yml
Will probably fail just after (can't reproduce locally, maybe a permission issue with alpine or runner)
> Fixing CI disabling entrypoint

- api/Dockerfile
| Tickets       | NA 
Not really sure about this one. I noticed the comment `# Workaround to allow using PHPUnit 8 with Symfony 4.3` and since this repo has upgraded to SF 5 this ENV var may have lost its value.
> fix(php): remove obsolete phpunit env var

- api/helm/api/templates/php-deployment.yaml
Update the php deployment to use the php replica count value instead of the Nginx one.
> Helm, use replica count of PHP for php-deployment

- api/helm/api/templates/php-deployment.yaml
When the PHP application is deployed, after 120 seconds the `readinessProbe` kicks in. `periodSeconds` is defined as `3` seconds, and the default value for `failureTreshold` is `3`, which means that 9 seconds after the probes kick in, the `pod` should be ready. If not, a `Failure` is registered and the `pod` will restart.
When the pod is started, the database migration is executed (defined in `/api/docker/php/docker-entrypoint.sh` in the codebase). The migration has to be done within the 129 seconds time limit, else the `pod` will restart during the migration.
This PR …
> [Kubernetes] Execute DB migration in initContainer

- api/docker/php/conf.d/api-platform.prod.ini
| New feature?  | yes
This adds opcache preload config for the prod php.ini as described [here](https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading)
It would be great to see this in 2.5.7 but I have created the PR against master because technically it's a new feature I guess.
> Add opcache preload config for Production.

- api/docker/php/docker-entrypoint.sh
We had some difficulties debuging an app. The error was that the php container didn't have the rights to reach the database in AWS (wrong security group documentation). 
The logs didn't help us enought to find the issue quickly. I suggest adding these two lines to help other people that may have the same problem to find out what's going on more easily.
> add more logs to docker php enttrypoint

- api/config/bootstrap.php
fix Since symfony/dotenv 5.1: Passing a boolean to the constructor of "Symfony\Component\Dotenv\Dotenv" is deprecated, use "Dotenv::usePutenv()"
| Deprecations? | yes
> fix Since symfony/dotenv 5.1: Passing a boolean to the constructor of "Symfony\Component\Dotenv\Dotenv" is deprecated, use "Dotenv::usePutenv()"

- api/config/packages/api_platform.yaml
- api/config/packages/security.yaml
The `stateless` attribute (https://github.com/api-platform/core/pull/3436) conflicts with a non-stateless firewall. Let's enable the `stateless` option of the firewall by default as it's a best practice for REST APIs. Also related: https://github.com/symfony/recipes/pull/853
> fix: enable the stateless firewall

- api/docker/caddy/Caddyfile
Let the API handling more requests including `/my-resources.jsonld`, `/my-resources.html` (Swagger UI or Twig controller) etc.
Also tell how to disable Next.js to let Symfony handling all requests.
> feat: allow more requests to be handled by the API

- api/docker/php/conf.d/api-platform.prod.ini
Fixed `opcache.preload`-option pointing to the wrong (and possibly non-existent) file
| Tickets       | none
| Doc PR        | none
When starting up the PHP-Container for the first time when downloading the latest version of API-Platform (Cloned the GitHub Template of the current alpha-tag), an error occured
Failed to open file /srv/api/var/cache/prod/App_KernelProdContainer.preload.php
I found the `preload.php` in the config, searched for it in the `api/` folder and realized it's not used, but it's loading exactly that file not found there, but only **if it exists** (since, it won't exist unless the platform is started in prod-env once)
I …
> Update opcache.preload option to point to the correct file

- .github/workflows/ci.yml
I've the feeling that this action slows down the CI instead of making it faster... Let's compare.
> fix: remove satackey/action-docker-layer-caching

- api/config/packages/api_platform.yaml
| Bug fix?      | no (2.6)
See @ https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L370
Also, @dunglas I have a couple of questions:
- Mercure within Caddy doesn't have cors configuration and throws errors due to invalid configuration (should I add one within this template?).
- Mercure heartbeat default configuration doesn't poll every 40s to be compatible with event-source-polyfill library, adding heartbeat 30s to Caddy configuration fixes it.
Happy new year!
> Fix deprecated http_cache.vary

- api/Dockerfile
Using composer:latest as `COPY --from` reference imposes the risk of colliding
with an already existing `composer:1.x` container. In that case, the `1.x` container will
be re-used. It will fail upon start with an unknown named parameter exception
This change pins the composer image in use to the `2.0` tag, meaning it will either
use an existing 2.0 container or pull the latest one.
> Force composer 2.0 for building the php container

- api/Dockerfile
```
api_platform\api> docker build --target api_platform_php -t php-api .
docker run --rm -it --entrypoint=sh php-api
/srv/api # ls /var/run/
/srv/api # php-fpm
[19-Jan-2021 07:59:48] ERROR: unable to bind listening socket for address '/var/run/php/php-fpm.sock': No such file or directory (2)
[19-Jan-2021 07:59:48] ERROR: FPM initialization failed
```
| Tickets       | fixes #1766
https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#connecting-nginx-to-php-fpm
```
If you’re using unix socket change fastcgi_pass to:
fastcgi_pass unix:/var/run/php-fpm.sock;
```
> Unable to bind listening socket for address '/var/run/php/php-fpm.sock

- pwa/pages/index.tsx
```sh
Failed to compile.
./pages/index.tsx:2674:18
Type error: Type '{ enableBackground: string; }' is not assignable to type 'CSSProperties'.
Object literal may only specify known properties, and 'enableBackground' does not exist in type 'CSSProperties'.
2672 |         height={25}
2673 |         viewBox="0 0 120 120"
> 2674 |         style={{ enableBackground: "new 0 0 120 120" }}
|                  ^
2675 |     >
2676 |         <style jsx>
2677 |             {`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` …
> Fix enableBackground not assignable to type CSSProperties

- pwa/.env
- pwa/Dockerfile
- pwa/pages/admin/index.tsx
| Tickets       | Fix #1844
This environment variable isn't necessary anymore.
> Remove REACT_APP_API_ENTRYPOINT

- api/Dockerfile
| Tickets       | Fix #1532
| Doc PR        | api-platform/docs#... 
Theres an issue with `iconv` in the `alpine` `php` distribution, resulting in errors like 
```
php Notice: iconv(): Wrong charset, conversion from UTF-8' to ASCII//TRANSLIT' is not allowed
```
If you use the `gnu-libiconv` package and change the `LD_PRELOAD` env var it works. There's no need to add any "unstable" repositories anymore. Tested with `php:8.0.3-fpm-alpine`.
From https://github.com/docker-library/php/issues/240#issuecomment-763112749
> fix: use gnu-libiconv package

- api/docker/php/docker-entrypoint.sh
| Deprecations? | ?
DoctrinBundle deprecated in v2.2 the Command "doctrine:query:sql" in the docker-entrypoint to check if database is available.
https://github.com/doctrine/DoctrineBundle/pull/1231
The recommended command is now "dbal:run-sql"
> fix deprecation warning for command "doctrine:query:sql" in docker-entrypoint

- api/docker/caddy/Caddyfile
| Tickets       | Related to https://github.com/symfony/symfony/issues/40835
Google’s Federated Learning of Cohorts is a new initiative to track internet users without their consent. This feature is already enabled by default for a small percentage of Google Chrome users, and is intended to be enabled for all users at the end of the experiment.
Developers can opt their websites out of FLoC by setting this HTTP header: `Permissions-Policy: interest-cohort=()`.
This PR sets this header by default in the API Platform distribution.
For more information about FLoC read [Google’s FLoC Is a Terrible …
> fix: disable Google FLoC tracking by default

- api/Dockerfile
- api/docker/caddy/Caddyfile
| Tickets       | Close https://github.com/api-platform/api-platform/issues/1881
See https://github.com/dunglas/mercure/pull/499.
> fix: ensure that the latest version of Mercure and Vulcain are always used

- api/docker/caddy/Caddyfile
Discussion in https://github.com/caddyserver/caddy/issues/4130 brought this up.
There's a bit of a gotcha here, in that having two `?Field` headers will append each to the `Require` response matcher, so those header fields will only be set if _both_ are not present in the response. If one is present (e.g. `Link` is in the response) then neither are set.
Using separate header handlers solves this because they will use their own handlers, and therefore separate response matchers.
This is just a followup to https://github.com/api-platform/api-platform/pull/1879 to fix this non-obvious behaviour.
| Branch?       | main 
| Tickets       | N/A 
> fix: header defaults in Caddyfile must be in separate handlers

- pwa/config/entrypoint.ts
The `dataAccess` module imports the `ENTRYPOINT` const, and not `NEXT_PUBLIC_ENTRYPOINT`:
https://github.com/api-platform/client-generator/blob/cf9663004bb839965c49b4db2de6d18bea696f74/templates/next/utils/dataAccess.ts#L5
> fix: export ENTRYPOINT in pwa/config/entrypoint.ts

- api/docker/php/php-fpm.d/zz-docker.conf
In the [helm chart](https://github.com/api-platform/api-platform/blob/main/helm/api-platform/templates/deployment.yaml#L139) its defined that when the pod is stopped, the `"/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"` commands are executed. I was quite curious who came up with that and why, and ended up reading [this](https://medium.com/flant-com/kubernetes-graceful-shutdown-nginx-php-fpm-d5ab266963c2) article. This was the only resource I could find explaining this exact command.
It perfectly explains the reason for this command, however it also states that it should be combined with the `process_control_timeout` directive. This PR adds the directive to the …
> fix: set php-fpm process_control_timeout

- helm/api-platform/values.yaml
| Tickets       | #2003
replicaCount always used the default value of 1 because of https://github.com/api-platform/api-platform/blob/7d8eb360592583a7b7ca76708c64c6d495e26383/helm/api-platform/templates/deployment.yaml#L9
> fix: replicaCount value in helm chart

- api/docker/caddy/Caddyfile
FLoC has been replaced by a new system called [The Topics API](https://github.com/jkarlin/topics). To disable this tracking, a new header is recommended: `Permissions-Policy: browsing-topics=()`.
> feat: disable Topics tracking

- api/docker/php/docker-entrypoint.sh
| Branch?       | 2.6.8
| Tickets       | None
The entrypoint only checks whether there are PHP files in the ./migrations directory but they can be generated in subdirectories when using the BY_YEAR or BY_YEAR_AND_MONTH configurations.
> fix: check for migrations in subdirectories

- helm/api-platform/Chart.lock
- helm/api-platform/Chart.yaml
| Tickets       | #2204 
This PR update the bundled postgresql chart version to the version `~10.16.2`.
The version currently used (`~10.1.4`) is no longer available in the Bitnami repository.
> Bugfix: update postgresql helm chart version

- api/Dockerfile
The latest official php images [are now based on Alpine 3.16](https://hub.docker.com/_/php?tab=tags&page=1&name=8.1-fpm-alpine), which ships with ICU 71.1 (vs 69.1 in Alpine 3.15).
This breaks date & currency formatting, since only english locale is now included by default.
> _The ICU data [has been split](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split) into [icu-data-en](https://pkgs.alpinelinux.org/packages?name=icu-data-en) (default) and [icu-data-full](https://pkgs.alpinelinux.org/packages?name=icu-data-full) packages. Users may need to install icu-data-full for non-English locales or legacy charset converters support._ …
> fix: alpine 3.16 support for `ext-intl`

- docker-compose.yml
When overwriting SERVER_NAME for production, keep caddy as secondary SERVER_NAME
> keep caddy as alternate server_name

- pwa/package.json
- pwa/yarn.lock
Tickets       |
To run the PWA code, (i.e. the next.js app) one needs to do the following:
```
cd pwa
yarn
yarn build
yarn start
```
However, `yarn build` gives this error:
```
error - ESLint must be installed in order to run during builds: yarn add --dev eslint
```
After running `yarn add --dev eslint` I ran `yarn build` again, and got this error:
```
error - ESLint: Failed to load config "react-app" to extend from. Referenced from: ./pwa/package.json
```
So I added that package: `yarn add eslint-config-react-app --dev`
After that, `yarn build` and `yarn start` ran without errors.
> Add missing yarn dependencies

- pwa/Dockerfile
It was added here without any explanation https://github.com/api-platform/api-platform/pull/1228 by @teohhanhui (if you have any comments - that would be very helpful)
Notes:
* Inside `api/Dockerfile` - there is no `VOLUME` for `vendor` folder, so it's not clear why we use `VOLUME` for JS application
* Because of this `VOLUME`, node modules folder is populated only inside docker volume, but **not on the host machine** during development. This required developers to run `yarn install` locally in order to have `node_modules` populated for IDE inspections
After this update, `node_modules` will work the same way as `vendor` folder works inside `api` app, so it will be shared thanks to docker bind-mount from `docker-compose.override.yaml`: …
> Do not create VOLUME for node_modules inside pwa/Dockerfile

- api/docker/caddy/Caddyfile
This directive is known to cause issues and is kind of useless anyway because Chrome will remove support for Server Push.
Note that this directive isn't related or used by Vulcain, and pushes triggered by Vulcain will still work.
> chore(caddy): remove the push directive

- api/docker/caddy/Caddyfile
The experimental_http3 server protocol option is now failing in Caddyfile as the option has been removed.
HTTP/3 support is now standard.
See…
- https://github.com/caddyserver/caddy/pull/4707
- https://github.com/caddyserver/caddy/pull/4707/files#diff-51e94e99e336177354509e6e1ea884faca26dd3e9ff0bc066581f2cc52df03deR195
| Branch?       | main (can't see any other branches to target as a bug fix)
It appears that support for the experimental_http3 server protocol option has been removed from Caddy.  [This PR](https://github.com/caddyserver/caddy/pull/4707/files#diff-51e94e99e336177354509e6e1ea884faca26dd3e9ff0bc066581f2cc52df03deR195) shows that the default options now include h3 …
> Removes experimental_http3 as now standard

- api/Dockerfile
Info : https://blog.codito.dev/2022/11/composer-binary-only-docker-images/
> build(dockerfile): use composer binary image

- api/docker/php/php-fpm.d/zz-docker.conf
| Tickets       | no ticket
| Doc PR        | no doc
Since PHP-FPM 8.2, it's possible to exclude some routes to log.
https://bugs.php.net/bug.php?id=80428
I think that logging the healthcheck route `/ping` is not useful and can be remove.
> remove /ping logs from php-fpm

- pwa/Dockerfile
PNPM 8 new release breaking change in lock file definition prevent building docker container
| Tickets       | #2417
| Doc PR        | api-platform
> Fixes #2417 : PNPM 8 new release breaking change

- helm/api-platform/templates/deployment.yaml
Before:
When the config map changed, the pods have to be restart manually to get the new configuration.
Proposition:
By adding an annotation in pods, they are restarted when the configmap change.
The annotation follow this documentation: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
> helm - update pod when configmap changed

- pwa/Dockerfile
| Tickets       | #2412
| Doc PR        | api-platform/docs
This PR is fixing the docker build issue with `--chown`, blocking the production image building.
> Fix for docker build issue for PWA

- .github/workflows/ci.yml
- api/Dockerfile
- docker-compose.override.yml
- docker-compose.prod.yml
- docker-compose.yml
- helm/api-platform/README.md
- pwa/Dockerfile
CI runs reduced from 5 to 7mn to about 1mn!
* Revamp PHP and Next.js `Dockerfile`s to improve caching
* Download a binary version of Caddy instead of compiling it locally
* Revamp the GitHub Actions workflow to use Docker Bake and cache layers in GitHub Actions' cache
> ci: improved Docker images and GitHub actions, CI execution time divided by 5!

- docker-compose.yml
This eases the process of using Docker Bake to build images needed for Kubernetes deployment.
This also allows us to easily push the images to a registry.
> feat: allow to prefix Docker images

- api/docker/caddy/Caddyfile
| Tickets       | Closes #..., closes #... 
Actually, any global Caddy option can be injected in the `CADDY_DEBUG`env var. Let's rename it to make this more intuitive.
Helps for https://github.com/api-platform/api-platform/pull/2487#issuecomment-1691308193.
> feat: rename CADDY_DEBUG to CADDY_GLOBAL_OPTIONS

- api/docker/php/docker-entrypoint.sh
In the typical case, vendors are already up to date. Skipping useless calls to composer install will speed up the boot time.
> feat: run composer install only if vendors aren't present

- README.md
In the README.md, the link https://api-platform.com/docs/distribution redirect to https://api-platform.com/docs/distribution/distribution/
> docs: fix link to documentation

- api/frankenphp/Caddyfile
I'm not sure if this is a fix or new feature
| Tickets       | Closes #2637
> feat: add ld+json encoding

- compose.yaml
Modifying the SERVER_NAME to disable HTTPS, as outlined in the [API Platform documentation](https://api-platform.com/docs/deployment/docker-compose/#disabling-https), leads to improper configurations for TRUSTED_HOSTS and MERCURE_PUBLIC_URL when using formats like `http://localhost` or `:80`. 
This results in values like `^:80|php$` or `^http://localhost|php$` for `TRUSTED_HOSTS`, and URLs such as `https://:80/.well-known/mercure` or `https://http://localhost/.well-known/mercure` for `MERCURE_PUBLIC_URL`. 
This PR adopts "nested interpolation" from the [Docker documentation](https://docs.docker.com/compose/compose-file/12-interpolation/) to allow precise overrides, introducing `TRUSTED_PROXIES` and `CADDY_MERCURE_PUBLIC_URL` as new, adjustable variables, with room for naming discussions.
> Allow overriding TRUSTED_HOSTS and MERCURE_PUBLIC_URL variables

- api/Dockerfile
- pwa/Dockerfile
| Branch?       | main (but bug fixes [^1])
> We recommend using docker/dockerfile:1, which always points to the latest stable release of the version 1 syntax, and receives both "minor" and "patch" updates for the version 1 release cycle.
https://docs.docker.com/build/buildkit/frontend/
Ported from https://github.com/dunglas/symfony-docker/pull/663
[^1]: I did not see the stable branch :(
> chore: do not specify minor version of Dockerfile syntax

- pwa/Dockerfile
When running `docker compose up` on a fresh installation, the node image and corepack version result in an "Cannot find matching keyid" error. Ensuring the latest corepack version resolves this.
| Tickets       | -
Creating a new repo with the current `main` state of this repo - by using [Github's green "use this template" button](https://github.com/api-platform/api-platform) - results in a build error when running `docker compose up`.
The following guide by Vercel suggests having the latest corepack version to resolve the error above: https://vercel.com/guides/corepack-errors-github-actions#quick-debug-steps
Macbook M1
Docker v4.38.0 (181591)
> Prefer latest corepack to prevent initial build error

- pwa/Dockerfile
FromAsCasing mismatch on AS and FROM keywords.
Docker build output:
| Tickets       | -
| Doc PR        | -
> Fix Docker build FromAsCasing mismatch warning

- pwa/Dockerfile
| Branch?       | main as unable to find a stable/latest branch to target
Updates the `adduser` command to specify the user's group ID.
Prior to this change, the build fails with error that group with ID 1001 already exists.
Sorry.  I'm unable to find stable/latest branch to target. Or the CHANGELOG.md file to update.
> fix: Correctly assign existing group ID to nextjs user

- helm/skaffold.yaml
| Branch?       | (unable to find stable/latest branch to target as advised, so `main`?branch for bug fixes 
Running `skaffold dev` was failing due to the build target not being found.  This appears to be because the target was renamed from `app_php` to `frankenphp_dev`.
I can only see `main` `api-platform-core` and `php-fpm` branches for targeting this PR, so unsure if this is correct based on the PR template advice.  Sorry if this is incorrect.
Also, I cannot see the CHANGELOG.md file that I'm advised to update.
I'm not sure if this reuqires tests, but please advise if it does, and where I might add these?
> fix: Update build target for php image in skaffold.yaml
