docker-compose.yaml
=> Init Docker environment

composer.json, composer.lock
| Fixed tickets | no
| Doc PR        | no
=> Use 2.3 for behatch/contexts

docker/apache/vhost.conf
=> Fix the xml schema of the vhost.conf

docker/apache/vhost.conf
Revert #66 and fix indentation that lead to this error.
=> Fix vhost conf

.travis.yml, Dockerfile, app/config/parameters.yml.dist, docker-compose.yml
| New feature?  | yes
| Fixed tickets | n/a
=> Fix Docker setup and add Travis setup

Dockerfile
Due to https://pear.php.net/bugs/bug.php?id=21008
=> Specify version of apcu to be installed

src/AppBundle/DataFixtures/ORM/book.yml
It exposes more API Platform features when playing with the default installation.
=> Increase the number of books in fixtures to enable the pagination

src/AppBundle/DataFixtures/ORM/book.yml
=> Fix Book::$title fixture generator

Dockerfile, docker/apache/run.sh, docker/apache/start_safe_perms, web/app_dev.php
* Fix permissions when running Docker for Mac
* Fix Vhost configuration
* Install composer securely
* Install dependencies to speed up the next download
=> Fix the Docker setup

app/config/routing.yml
This needs to be removed following the updates in the core.
=> Remove the Swagger routing

app/autoload.php, bin/console, web/app.php, web/app_dev.php
Following symfony/symfony-standard#990
=> Change inline var PHPDoc syntax

Dockerfile, composer.lock, docker/composer.sh
I really want to change how we are using docker.
This could be directly pushed into an image that would not lead to this issue.
=> hotfix: fix composer updating

CONTRIBUTING.md, Dockerfile
=> Improve Docker support on Windows

web/app_dev.php
See symfony/symfony-standard#937
=> Fix IP whitelist in app_dev.php

.travis.yml, docker-compose.yml
Signed-off-by: David McKay <david@rawkode.com>
=> Modernising docker-compose configuration

Dockerfile
=> Add PCRE dependency to the docker build for the php image.

Dockerfile
Reverts api-platform/api-platform#299
See https://github.com/api-platform/api-platform/issues/298#issuecomment-301399836 and https://github.com/api-platform/api-platform/issues/298#issuecomment-301401182
=> Revert "Add PCRE dependency to the docker build for the php image."

docker/nginx/conf.d/default.conf
=> Fix Nginx's config

app/config/config.yml, app/config/parameters.yml.dist, composer.json, composer.lock, docker-compose.yml, docker/varnish/Dockerfile, docker/varnish/conf/default.vcl, docker/varnish/start.sh, web/app.php, web/app_dev.php
See api-platform/core#952 for the rationale.
TODO:
=> Add a Varnish container and enable cache invalidation

docker-compose.yml
It is hard in mac to use the old docker configuration, so we have to update to gain perf.
=> hotfix: fix docker configuration

composer.lock
https://symfony.com/blog/cve-2017-11365-empty-passwords-validation-issue
And fix Travis btw...
=> Upgrade to Symfony 3.3.5 to fix CVE-2017-11365

api/.gitignore, api/.php_cs.dist, api/composer.json, api/composer.lock, api/config/packages/doctrine.yaml, api/docker/varnish/conf/default.vcl, api/symfony.lock, docker-compose.yaml
Downgrade required by doctrine/dbal#2893.
=> Bump deps. Downgrade to Postgres 9.6.

api/Dockerfile
Applying same method as upstream docker php image.
=> Use scanelf to detect runtime deps

docker-compose.yaml
=> Use the cached mode for some Docker volumes

api/.php_cs.dist
| Fixed tickets | N/A
The current config is non-functional.
=> Fix PHP-CS-Fixer config

.travis.yml, api/Dockerfile, api/composer.lock
| Fixed tickets | N/A
Now the composer.lock content-hash should match.
=> Minor enhancements for php Dockerfile

api/.env.dist
=> feature: add .env.dist

.travis.yml
Since it is no longer necessary after #665...
=> Don't use sh to run command

.gitattributes
=> Better eol conversion in .gitattributes

api/Dockerfile
=> Use alpine image for varnish

.travis.yml, docker-compose.yml
And actually reuse previously built images in CI
=> Make the Docker build caching more robust

client/src/Welcome.js
Useful when using a custom domain name for development.
=> Use the current domain name in Welcome.js

.travis.yml, api/.env, api/composer.json, api/composer.lock, api/config/bundles.php, api/config/packages/api_platform.yaml, api/config/packages/mercure.yaml, api/config/services.yaml, api/symfony.lock, docker-compose.yml, h2-proxy/conf.d/default.conf
Do not merge yet, should be merged only when API Platform 2.4 beta will be released.
=> Add Mercure support

docker-compose.yml
Previous links point to a 'this section has moved ...' sentence.
| Fixed tickets | -
| Doc PR        | -
=> Update react static website links hint

api/Dockerfile
This package is now useless thanks to Flex.
=> Remove hirak/prestissimo

docker-compose.yml
=> User YAML merge keys to avoid duplications

api/.env, api/.gitignore, api/config/packages/test/routing.yaml, api/src/Kernel.php, api/symfony.lock, update-deps.sh
After installing the project, I made an update of the recipes with `composer sync-recipes --force`
That's what it gives, tell me if there are things to remove.
Q | A
-- | --
Bug fix? | no
New feature? | no
BC breaks? | no
Deprecations? | no
Tests pass? | yes
Fixed tickets |  
License | MIT
Doc PR
=> Bump recipe

api/Dockerfile
Notable enhancements:
https://github.com/docker-library/php/pull/725
https://github.com/docker-library/php/pull/763
=> Upgrade to PHP 7.3

api/.dockerignore, api/Dockerfile
Because of this PR: https://github.com/symfony/recipes/pull/588
=> Fix builds

admin/yarn.lock, api/composer.json, api/composer.lock, api/config/packages/test/validator.yaml, api/config/packages/validator.yaml, api/src/Entity/Greeting.php, api/symfony.lock, client/yarn.lock, update-deps.sh
=> Upgrade to Symfony 4.3

api/composer.json, api/composer.lock, api/config/bundles.php, api/symfony.lock
It allows to generate API Platform resources classes directly from the command line: `bin/console make:entity`
=> Add MakerBundle

docker-compose.yml
Allow to use Mercure using HTTPS in dev.
=> Expose Mercure through the TLS proxy

.github/CODE_OF_CONDUCT.md
|Question             | Answer
=> Make hyperlink more readable in Code of Conduct

.github/CONTRIBUTING.md
Once a Pull Request Template is created, update CONTRIBUTING
=> Update CONTRIBUTING.md to reflect pull request template

admin/package.json, admin/yarn.lock, client/package.json, client/yarn.lock
This changes Update `react-scripts` dependency to latest version `3.1.2`
Fixes #1263 
@douglas @alanpoulain
=> deps(react): update react scripts to latest version

.github/CODE_OF_CONDUCT.md
=> Feat: remove coc file

.github/CONTRIBUTING.md
| Bug fix?      | yes (in docs) 
=> fixed broken link for LICENSE file

api/Dockerfile
=> Bump APCu to 5.1.18

api/docker/varnish/conf/default.vcl
=> Skip vulcain headers from varnish request

api/Dockerfile, api/docker/php/docker-healthcheck.sh, docker-compose.yml
| Tickets       | fixes #1295  
Add healthcheck in php container see #1295
=> Add healthcheck php-fpm

api/docker/varnish/conf/default.vcl
Reverts api-platform/api-platform#1337
See https://github.com/api-platform/api-platform/pull/1337#discussion_r349871189
=> Revert "Skip vulcain headers from varnish request"

.github/workflows/ci-cd.yml, README.md, api/helm/api/values.yaml, docker-compose.yml
GitHub Packages requires auth even for pulling, so it's not ideal for a public registry.
TODO:
=> Switch back to quay.io

.github/workflows/ci-cd.yml
=> Update actions/checkout to v2

api/.env, api/.gitignore, api/Dockerfile, api/bin/console, api/composer.json, api/composer.lock, api/config/packages/cache.yaml, api/config/packages/doctrine.yaml, api/config/packages/prod/doctrine.yaml, api/config/packages/security.yaml, api/config/packages/twig.yaml, api/config/routes/dev/framework.yaml, api/public/index.php, api/src/Kernel.php, api/symfony.lock
| New feature?  | yes
| Tickets       | fixes #1368 
| Doc PR        | _N/A_
Using Symfony 4.4 by default, instead of Symfony 4.3.
=> Use Symfony 4.4 by default

.github/workflows/ci-cd.yml
=> Bump docker-compose to 1.25.2

api/.env, api/docker/php/docker-entrypoint.sh, docker-compose.yml, docker/dev-tls/Dockerfile, update-deps.sh
| Tickets       | fixes #1405
Cleaner alternative to #1414
=> Add the local (dev) CA cert to CA cert store of php container

api/config/packages/nelmio_cors.yaml
=> CORS: whitelist Vulcain headers

.github/workflows/ci-cd.yml
=> Enable inline cache for buildx bake

api/composer.json, api/composer.lock, api/config/routes/dev/twig.yaml
| BC breaks?    | yes
Upgrade Symfony to v5.0
=> Upgrade Symfony to 5.0

.editorconfig, api/.gitignore, api/Dockerfile, api/composer.lock, api/docker/nginx/conf.d/default.conf, api/helm/api/.helmignore, api/helm/api/Chart.yaml, api/helm/api/requirements.lock, api/helm/api/requirements.yaml, api/helm/api/templates/NOTES.txt, api/helm/api/templates/_helpers.tpl, api/helm/api/templates/configmap.yaml, api/helm/api/templates/ingress.yaml, api/helm/api/templates/nginx-deployment.yaml, api/helm/api/templates/nginx-service.yaml, api/helm/api/templates/php-deployment.yaml, api/helm/api/templates/php-service.yaml, api/helm/api/templates/secrets.yaml, api/helm/api/templates/serviceaccount.yaml, api/helm/api/templates/tests/test-connection.yaml, api/helm/api/templates/varnish-deployment.yaml, api/helm/api/templates/varnish-service.yaml, api/helm/api/values.yaml
Upgrade the Helm chart for v3. Also improve its general architecture.
=> Improve Helm chart and upgrade to v3

api/helm/api/templates/php-deployment.yaml
| Tickets       | fixes #1478 
Hello, I tried the last commit (#1478) on master about Helm v2 to v3 and I got a little issue during the deployment in my K8s cluster as you can see. 
Curly braces where missing 
Os: Linux mint 19.3
Helm version : 3.1.2
=> Fix helm php-deployment file. (ref pull #1478)

api/Dockerfile
=> deps(varnish): update varnish to 6.4

.github/workflows/ci-cd.yml
=> Bump docker buildx from 0.3.1 to 0.4.1

api/helm/api/templates/php-deployment.yaml
There is no /bin/bash in the image, use /bin/sh
=> fix helm php-deployment.yaml initContainers

api/.env.test, api/.gitignore, api/Dockerfile, api/bin/console, api/bin/phpunit, api/composer.json, api/composer.lock, api/config/bundles.php, api/config/packages/dev/debug.yaml, api/config/packages/dev/monolog.yaml, api/config/packages/prod/deprecations.yaml, api/config/packages/prod/monolog.yaml, api/config/packages/routing.yaml, api/config/packages/security.yaml, api/config/packages/test/monolog.yaml, api/phpunit.xml.dist, api/public/index.php, api/src/Kernel.php, api/symfony.lock, api/tests/bootstrap.php
=> feat: upgrade to Symfony 5.1

api/Dockerfile, api/docker/varnish/conf/default.tmpl, api/docker/varnish/docker-entrypoint.sh, api/helm/api/Chart.yaml, api/helm/api/templates/NOTES.txt, api/helm/api/templates/configmap.yaml, api/helm/api/templates/ingress.yaml, api/helm/api/templates/nginx-service.yaml, api/helm/api/templates/php-deployment.yaml, api/helm/api/templates/secrets.yaml, api/helm/api/templates/tests/test-connection.yaml, api/helm/api/templates/varnish-deployment.yaml, api/helm/api/values.yaml
| Tickets       |
Helm configuration tested and fixed at https://github.com/api-platform/demo/pull/155
=> Fix helm configuration

api/helm/api/templates/configmap.yaml
=> Fix Helm lint

api/Dockerfile
| Bug fix?      |  no 
| Tickets       | n/a| License       | MIT
=> Bump APCU and Varnish versions

api/docker/caddy/Caddyfile
=> feat: store Mercure DB in a volume

api/Dockerfile, api/composer.json, api/composer.lock, api/symfony.lock
=> feat: upgrade to Symfony 5.2

api/.env, api/config/packages/api_platform.yaml, api/config/packages/doctrine.yaml, api/config/packages/framework.yaml, api/config/preload.php, api/public/index.php, api/src/Kernel.php, api/symfony.lock, pwa/yarn.lock, update-deps.sh
=> feat: sync recipes

api/.env
| Tickets       | fixes https://github.com/api-platform/api-platform/pull/1697#pullrequestreview-542638958
| Doc PR        | ~
=> fix (.env): typo in DATABASE_URL

pwa/pages/admin/index.js
=> fix: admin's title

api/.env, api/src/Entity/Greeting.php
=> fix: Mercure publish URL

api/Dockerfile, api/composer.json, api/composer.lock, api/docker/caddy/Caddyfile, docker-compose.override.yml, docker-compose.prod.yml, helm/api-platform/templates/deployment.yaml
=>  feat: bump deps 

api/Dockerfile, api/composer.lock, api/docker/php/docker-entrypoint.sh, api/symfony.lock
| Tickets       | n:a
All the dependencies we need are now stable and compatible with PHP 8!
=> bumps deps

api/docker/caddy/Caddyfile, docker-compose.yml, pwa/next-env.d.ts, pwa/package.json, pwa/pages/index.js, pwa/tsconfig.json, pwa/yarn.lock
| Tickets       | fixes https://github.com/api-platform/api-platform/issues/1726
=> fix: Caddyfile and default JS deps for the PWA

.editorconfig
=> refactor: remove useless entries in .editorconfig

api/docker/caddy/Caddyfile
=> Forward sitemap request to PWA instead of Symfony

api/Dockerfile, api/docker/php/docker-entrypoint.sh
=> feat: allow to use the Docker setup without DB

.github/workflows/ci.yml, api/Dockerfile, api/docker/caddy/Caddyfile, docker-compose.override.yml, docker-compose.yml
=> fix: Caddy build

.github/workflows/ci.yml, api/docker/php/docker-entrypoint.sh
| Tickets       | fixes #1656, fixes #1536
Display more descriptive error messages in case of error.
Before:
```
php_1       | Still waiting for database to be ready... Or maybe the database is not reachable. 1 attempts left.
php_1       | Still waiting for database to be ready... Or maybe the database is not reachable. 0 attempts left.
php_1       | The database is not up or not reachable.
```
After:
```
php_1       | Still waiting for database to be ready... Or maybe the database is not reachable. 1 attempts left.
php_1       | Still waiting for database to be ready... Or maybe the database is not reachable. 0 …
```
=> ci: improve debugging experience

.github/workflows/ci.yml, api/docker/caddy/Caddyfile, api/docker/php/docker-entrypoint.sh
=> refactor: tiny improvements in Caddyfile and in the entrypoint

api/.env.test, api/Dockerfile, api/phpunit.xml.dist, api/tests/Api/GreetingsTest.php
=> fix: functional tests

api/.env, api/.php_cs.dist, api/composer.json, api/composer.lock, api/symfony.lock, pwa/yarn.lock, update-deps.sh
=> feat: bump deps

api/docker/php/docker-entrypoint.sh
Backport of https://github.com/dunglas/symfony-docker/pull/110.
=> fix: do not check DB availability if code errors

api/tests/Api/GreetingsTest.php, pwa/yarn.lock
=> fix: namespace of GreetingsTest

pwa/Dockerfile
=> fix: missing API_PLATFORM_CLIENT_GENERATOR_OUTPUT

api/src/Entity/Greeting.php
=> Use the NotBlank attribute

api/docker/caddy/Caddyfile
=> Simplify Caddyfile

api/.env.test, api/composer.lock, api/phpunit.xml.dist, api/symfony.lock, pwa/yarn.lock
=> Bump dependencies

pwa/pages/index.tsx
Thanks for the logo @CecileAmrl!
=> add a link to the Mercure debugger from the Welcome page

api/composer.lock
Fixes #1824 (see https://github.com/composer/composer/issues/9722)
| Branch?       | main for features 
| Tickets       | Fix #1824  
=> Update symfony/flex (v1.12.1 => v1.12.2)

docker-compose.override.yml
=> Remove useless ports definition in docker-compose.override.yml

api/.env, api/composer.lock, api/symfony.lock, pwa/yarn.lock
=> feat: bump dependencies

api/docker/php/conf.d/api-platform.prod.ini
Backport of https://github.com/dunglas/symfony-docker/pull/116.
=> feat: don't expose PHP in prod

api/Dockerfile, api/docker/caddy/Caddyfile
=> fix: add Vulcain back

.github/workflows/ci.yml, api/.env, api/.gitignore, api/bin/console, api/bin/phpunit, api/composer.json, api/composer.lock, api/config/packages/framework.yaml, api/config/packages/prod/routing.yaml, api/config/packages/routing.yaml, api/config/packages/security.yaml, api/config/packages/test/doctrine.yaml, api/config/packages/test/framework.yaml, api/config/packages/test/twig.yaml, api/config/packages/twig.yaml, api/config/routes/dev/framework.yaml, api/config/routes/dev/twig.yaml, api/config/routes/framework.yaml, api/config/services.yaml, api/phpunit.xml.dist, api/public/index.php, api/src/Kernel.php, api/symfony.lock, api/templates/base.html.twig, pwa/yarn.lock, update-deps.sh
Bump symfony 5.2 to 5.3
Bump >=8.0 to >=8.0.2
Symfony 6 is using this, so i guess they avoid some bugs in 8.0.0 and 8.0.1
https://github.com/symfony/symfony/blob/6.0/composer.json
=> Add symfony 5.3

api/.env, api/composer.lock, api/config/packages/api_platform.yaml, api/phpunit.xml.dist, api/symfony.lock, pwa/yarn.lock
=> chore: bump deps

README.md
=> fix: small typo in README.md

api/Dockerfile, docker-compose.override.yml
=> fix: compatibility with Mercure 0.12

api/Dockerfile, api/composer.lock, api/config/packages/doctrine.yaml, api/config/packages/prod/doctrine.yaml, api/config/packages/security.yaml, api/migrations/Version20210930074739.php, api/phpunit.xml.dist, api/src/Entity/Greeting.php, api/symfony.lock, pwa/Dockerfile, pwa/yarn.lock, update-deps.sh
=> feat: enable attributes for Doctrine

api/Dockerfile
Fixed compatibility with PHP 8.1 by adding return types to APCUIterator.
=> feat: Update apcu version in Dockerfile

api/docker/caddy/Caddyfile
=> feat: add /contexts in Caddyfile

api/Dockerfile, api/docker/php/conf.d/api-platform.dev.ini, api/docker/php/conf.d/api-platform.prod.ini, api/docker/php/docker-entrypoint.sh
Tweak PHP config according to Blackfire's recommendation.
See https://github.com/dunglas/symfony-docker/pull/266
=> feat: improve PHP config

api/.dockerignore, api/Dockerfile, api/docker/caddy/Caddyfile, api/docker/php/conf.d/api-platform.dev.ini, api/docker/php/conf.d/api-platform.ini, api/docker/php/conf.d/api-platform.prod.ini, api/docker/php/docker-entrypoint.sh, docker-compose.override.yml, docker-compose.prod.yml, docker-compose.yml, pwa/.dockerignore, pwa/Dockerfile
See https://github.com/dunglas/symfony-docker/pull/271
=> feat: add native Xdebug support

helm/api-platform/templates/deployment.yaml
<!--
Replace long initialDelaySeconds in liveness and readiness probes by startupProbe to reduce startup time
=> helm: replace initialDelaySeconds by startupProbe

pwa/Dockerfile
=> fix: PWA's Dockerfile

api/docker/caddy/Caddyfile
=> fix: route json* requests to the API

.github/workflows/ci.yml
=> ci: test PWA reachability

api/.env, api/Dockerfile, api/composer.json, api/composer.lock, api/config/packages/debug.yaml, api/config/packages/doctrine.yaml, api/config/packages/doctrine_migrations.yaml, api/config/packages/framework.yaml, api/config/packages/monolog.yaml, api/config/packages/security.yaml, api/config/packages/validator.yaml, api/config/packages/web_profiler.yaml, api/config/routes.yaml, api/config/routes/web_profiler.yaml, api/config/services.yaml, api/symfony.lock, docker-compose.yml, pwa/Dockerfile, pwa/package.json, pwa/pages/index.tsx, pwa/pnpm-lock.yaml
=> feat: improve Dockerfile and bump deps

docker-compose.override.yml, docker-compose.yml
=> fix: create client env vars and dev php.ini

pwa/components/common/Layout.tsx, pwa/pages/_app.tsx
We need to update this page too: https://api-platform.com/docs/main/create-client/nextjs/
=> fix: react-query installation

api/composer.json
| Branch?       | 3.0
| Tickets       | #2260
=> fix: Dependency to core is set to dev-main

api/docker/caddy/Caddyfile
| Tickets       | -
| Doc PR        | -
https://github.com/dunglas/frankenphp/pull/79#pullrequestreview-1162649492
=> feat: rename DEBUG to CADDY_DEBUG

api/Dockerfile, api/composer.json, api/composer.lock
Upgrade to PHP 8.2 and bump deps. Also closes #2339 and #2340.
=> feat: upgrade to PHP 8.2

api/Dockerfile
Port of https://github.com/dunglas/symfony-docker/pull/298.
Uses https://github.com/mlocati/docker-php-extension-installer.
=> feat: use mlocati/php-extension-installer

pwa/package.json, pwa/pnpm-lock.yaml
=> fix: PWA dependencies

pwa/package.json, pwa/pages/index.tsx, pwa/pnpm-lock.yaml
=> feat: upgrade to Next 13

api/composer.lock, api/config/packages/doctrine.yaml, api/symfony.lock
=> chore: upgrade recipes

pwa/Dockerfile
| Tickets       | Closes #2352 
=> fix(pwa): location of the PNPM store

.github/workflows/ci.yml, api/Dockerfile, pwa/Dockerfile
=> Lint Dockerfiles

pwa/Dockerfile
Ensure that builds are reproducible.
=> ci(pwa): use frozen PNPM lockfile

pwa/Dockerfile
See https://github.com/vercel/next.js/pull/52804.
=> feat(pwa): add support for HOSTNAME in Docker images

README.md
=> docs: fix logo and some typos

docker-compose.override.yml, docker-compose.prod.yml
Backport of https://github.com/dunglas/symfony-docker/pull/376, thanks @maidmaid.
=> feat: watch Caddyfile in dev env

api/composer.json, api/composer.lock, api/config/packages/api_platform.yaml, api/symfony.lock, api/tests/Api/GreetingsTest.php
=> chore: upgrade chore to 3.2 beta 1

api/frankenphp/conf.d/app.ini
| Tickets       | https://github.com/dunglas/symfony-docker/issues/470
=> fix: sessions and cookies support

api/Dockerfile
| Branch?       | main for features / current stable version branch for bug fixes 
Thanks to https://github.com/dunglas/frankenphp/pull/223
=> feat: switch back to Alpine

.editorconfig, api/frankenphp/Caddyfile, compose.override.yaml
| Branch?       | main for features / current stable version branch for bug fixes 
* Cleaner `Caddyfile`
* Human-readable logs in dev mode (`tty: true`)
=> refactor: improve Caddy config

api/config/packages/doctrine.yaml, api/symfony.lock, pwa/package.json, pwa/pnpm-lock.yaml
=> chore: upgrade Doctrine recipe and bump JS deps

api/Dockerfile, compose.yaml
=> chore: backport fixes and improvements from Symfony Docker

api/frankenphp/Caddyfile
=> feat: add Brotli compression support

update-deps.sh
| Tickets       | Closes n/a
| Doc PR        | api-platform/docs#... 
This should prevent the recent problems we had.
=> chore: run tests as part of update-deps.sh

api/Dockerfile
| Tickets       | https://github.com/dunglas/symfony-docker/issues/555
Port of https://github.com/dunglas/symfony-docker/pull/582.
=> feat: switch to Debian instead of Alpine

helm/api-platform/Chart.yaml, helm/api-platform/templates/secrets.yaml
Update Postgresql to 16.2  on Helm like on Composer and .env
=> Helm postgresql 16

api/frankenphp/docker-entrypoint.sh
https://github.com/dunglas/symfony-docker/pull/613
=> feat: use the --all-or-nothing flags for migrations

.gitattributes, api/frankenphp/Caddyfile
Simplify config and remove dev files from the template.
=> chore: simplify config (Caddy 2.8)

compose.yaml
Synchronize the Doctrine Docker config with the latest version of the Symfony recipe.
=> chore: upgrade Postgres Docker config

pwa/components/admin/App.tsx, pwa/pages/admin/index.tsx
=> Facilitate admin customization

pwa/package.json, pwa/pnpm-lock.yaml
Also removes a remaining develop/debug statement in `package.json`.
Closes #2746.
=> chore: bump PWA deps

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/release.yml, api/.env, api/Dockerfile, api/composer.json, api/composer.lock, api/config/packages/doctrine.yaml, api/config/packages/framework.yaml, api/config/packages/routing.yaml, api/config/packages/validator.yaml, api/symfony.lock, e2e/package-lock.json, e2e/package.json, pwa/Dockerfile
=> feat: upgrade to Symfony 7
